(() => {
  'use strict';
  const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
  const readJSON=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(f));}catch{return f;}};
  const state={route:'home',folder:'',query:'',items:[],folders:[],stats:{},hasMore:false,current:null,pack:null,packIndex:0,tagTarget:null,requestToken:0,favorites:new Set(readJSON('localhub:favorites',[])),progress:readJSON('localhub:progress',{})};
  const el={grid:$('#grid'),title:$('#pageTitle'),meta:$('#pageMeta'),hint:$('#viewHint'),empty:$('#empty'),more:$('#loadMore'),folderNav:$('#folderNav'),search:$('#searchInput'),clearSearch:$('#clearSearch'),rescan:$('#rescanBtn'),brand:$('#brandBtn'),viewer:$('#viewer'),closeViewer:$('#closeViewer'),video:$('#videoPlayer'),viewerTitle:$('#viewerTitle'),viewerPath:$('#viewerPath'),viewerTags:$('#viewerTags'),favorite:$('#favoriteBtn'),manage:$('#manageBtn'),managePanel:$('#managePanel'),manageTags:$('#manageTags'),saveTags:$('#saveTags'),renameInput:$('#renameInput'),renameBtn:$('#renameBtn'),moveInput:$('#moveInput'),moveBtn:$('#moveBtn'),reader:$('#reader'),closeReader:$('#closeReader'),readerImage:$('#readerImage'),readerTitle:$('#readerTitle'),readerCounter:$('#readerCounter'),readerPrev:$('#readerPrev'),readerNext:$('#readerNext'),tagDialog:$('#tagDialog'),closeTagDialog:$('#closeTagDialog'),cancelTagDialog:$('#cancelTagDialog'),tagDialogName:$('#tagDialogName'),tagDialogInput:$('#tagDialogInput'),saveTagDialog:$('#saveTagDialog'),toast:$('#toast')};

  let thumbObserver=null,thumbQueue=[],thumbActive=0,thumbGen=0,searchTimer=null,lastProgressWrite=0;
  const controllers=new Set(),objectUrls=new Set();
  const esc=(s='')=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const bytes=(n=0)=>{const u=['B','KB','MB','GB','TB'];let x=Number(n)||0,i=0;while(x>=1024&&i<u.length-1){x/=1024;i++;}return `${x>=10||i===0?x.toFixed(0):x.toFixed(1)} ${u[i]}`;};
  const toast=m=>{el.toast.textContent=m;el.toast.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.toast.classList.remove('show'),2000);};
  const saveFav=()=>localStorage.setItem('localhub:favorites',JSON.stringify([...state.favorites]));
  const saveProgress=()=>localStorage.setItem('localhub:progress',JSON.stringify(state.progress));
  async function api(url,opt={}){const r=await fetch(url,{cache:'no-store',...opt});let d={};try{d=await r.json();}catch{}if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);return d;}
  const manage=p=>api('/api/manage',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)});

  function clearThumbWork(){thumbGen++;thumbQueue=[];for(const c of controllers)c.abort();controllers.clear();thumbActive=0;if(thumbObserver){thumbObserver.disconnect();thumbObserver=null;}for(const u of objectUrls)URL.revokeObjectURL(u);objectUrls.clear();}
  function ensureObserver(){if(thumbObserver)return;thumbObserver=new IntersectionObserver(entries=>{const gen=thumbGen;for(const e of entries){if(!e.isIntersecting)continue;thumbObserver.unobserve(e.target);thumbQueue.push({img:e.target,gen});}pumpThumbs();},{rootMargin:'320px 0px',threshold:.01});}
  async function pumpThumbs(){while(thumbActive<2&&thumbQueue.length){const job=thumbQueue.shift();if(!job||job.gen!==thumbGen||!job.img.isConnected)continue;thumbActive++;const c=new AbortController();controllers.add(c);try{const r=await fetch(job.img.dataset.thumb,{cache:'no-store',signal:c.signal});if(!r.ok)throw new Error();const blob=await r.blob();if(job.gen!==thumbGen||!job.img.isConnected)continue;const u=URL.createObjectURL(blob);objectUrls.add(u);job.img.src=u;job.img.classList.add('loaded');}catch(e){if(e.name!=='AbortError')job.img.closest('.thumb')?.classList.add('thumb-failed');}finally{controllers.delete(c);thumbActive=Math.max(0,thumbActive-1);pumpThumbs();}}}
  function observeNewThumbs(root=el.grid){ensureObserver();root.querySelectorAll('img[data-thumb]:not([data-thumb-observed])').forEach(img=>{img.dataset.thumbObserved='1';thumbObserver.observe(img);});}

  function pct(item){const p=state.progress[item.id];return p?.duration?Math.max(0,Math.min(100,p.time/p.duration*100)):0;}
  function tagHtml(item){if(!['video','image'].includes(item.kind))return '';const chips=(item.tags||[]).slice(0,3).map(t=>`<button class="tag-chip" data-tag="${esc(t)}">#${esc(t)}</button>`).join('');return `<div class="tag-strip" data-tag-strip="${esc(item.id)}">${chips||'<span class="no-tags">暂无标签</span>'}<button class="tag-edit" data-edit-tags="${esc(item.id)}">＋</button></div>`;}
  function mediaCard(item){const p=pct(item),fav=state.favorites.has(item.id);return `<article class="card clickable" data-id="${esc(item.id)}"><div class="thumb ${item.kind==='video'?'video-thumb':''}"><div class="thumb-placeholder">准备预览</div><img data-thumb="${esc(item.thumb)}" alt="" decoding="async"><span class="badge">${item.kind==='video'?'视频':'图片'}</span><span class="badge ext">${esc((item.ext||'').toUpperCase())}</span><button class="favorite-star ${fav?'on':''}" data-fav="${esc(item.id)}">★</button>${p?`<div class="progress"><i style="width:${p}%"></i></div>`:''}</div><div class="card-title" title="${esc(item.name)}">${esc(item.name)}</div>${tagHtml(item)}<div class="card-meta"><span>${bytes(item.size)}</span><span>${esc(item.folder||'根目录')}</span></div></article>`;}
  const folderCard=i=>`<article class="card folder-card clickable" data-folder="${esc(i.path)}"><div class="thumb"><div class="folder-glyph">▰</div><span class="badge">文件夹</span></div><div class="card-title">${esc(i.name)}</div><div class="card-meta"><span>${i.videos} 视频</span><span>${i.images} 图片</span></div></article>`;
  const packCard=i=>`<article class="card pack-card clickable" data-pack="${esc(i.folder)}"><div class="thumb"><div class="thumb-placeholder">图册封面</div><img data-thumb="${esc(i.coverThumb||i.cover)}" alt="" decoding="async"><span class="pack-count">${i.count} 张</span></div><div class="card-title">${esc(i.name)}</div><div class="card-meta"><span>图包 / 图册</span><span>${esc(i.folder||'根目录')}</span></div></article>`;
  const cardHtml=i=>i.kind==='folder'?folderCard(i):i.kind==='pack'?packCard(i):mediaCard(i);

  function renderFull(){clearThumbWork();el.grid.innerHTML=state.items.map(cardHtml).join('');afterRender();}
  function appendCards(batch){if(!batch.length)return;const box=document.createElement('div');box.innerHTML=batch.map(cardHtml).join('');const frag=document.createDocumentFragment();while(box.firstChild)frag.appendChild(box.firstChild);el.grid.appendChild(frag);afterRender();}
  function afterRender(){el.empty.classList.toggle('hidden',state.items.length>0);el.more.classList.toggle('hidden',!state.hasMore);bindCards();observeNewThumbs();}
  function bindCards(){
    el.grid.querySelectorAll('.card:not([data-bound])').forEach(card=>{card.dataset.bound='1';card.onclick=e=>{if(e.target.closest('[data-fav],[data-edit-tags],[data-tag]'))return;if(card.dataset.folder!==undefined)return openFolder(card.dataset.folder);if(card.dataset.pack!==undefined)return openPack(card.dataset.pack);const item=state.items.find(x=>x.id===card.dataset.id);if(item){item.kind==='video'?openViewer(item):openSingleImage(item);}};});
    el.grid.querySelectorAll('[data-fav]:not([data-bound])').forEach(b=>{b.dataset.bound='1';b.onclick=e=>{e.stopPropagation();toggleFavorite(b.dataset.fav);b.classList.toggle('on',state.favorites.has(b.dataset.fav));};});
    el.grid.querySelectorAll('[data-edit-tags]:not([data-bound])').forEach(b=>{b.dataset.bound='1';b.onclick=e=>{e.stopPropagation();const i=state.items.find(x=>x.id===b.dataset.editTags);if(i)openTagDialog(i);};});
    el.grid.querySelectorAll('[data-tag]:not([data-bound])').forEach(b=>{b.dataset.bound='1';b.onclick=e=>{e.stopPropagation();el.search.value=b.dataset.tag;searchNow(b.dataset.tag);};});
  }
  function updateTagStrip(item){const old=el.grid.querySelector(`[data-tag-strip="${CSS.escape(item.id)}"]`);if(!old)return;const box=document.createElement('div');box.innerHTML=tagHtml(item);old.replaceWith(box.firstElementChild);bindCards();}

  function navActive(route){$$('.main-nav button').forEach(b=>b.classList.toggle('active',b.dataset.route===route));$$('.folder-nav button').forEach(b=>b.classList.toggle('active',route==='folder'&&b.dataset.folder===state.folder));}
  function renderFolders(){el.folderNav.innerHTML=state.folders.map(f=>{const depth=Math.min(2,(f.path.match(/\//g)||[]).length);return `<button class="depth-${depth}" data-folder="${esc(f.path)}"><span>▸ ${esc(f.name)}</span><small>${f.videos||f.images}</small></button>`;}).join('')||'<div class="side-loading">没有文件夹</div>';el.folderNav.querySelectorAll('button').forEach(b=>b.onclick=()=>openFolder(b.dataset.folder));}

  async function loadHome(){const token=++state.requestToken;state.route='home';state.folder='';state.query='';state.hasMore=false;navActive('home');el.title.textContent='首页';el.meta.textContent='正在读取轻量索引…';el.hint.textContent='最多 15 个视频';const d=await api('/api/smart/home');if(token!==state.requestToken)return;state.items=d.items||[];state.folders=d.folders||[];state.stats=d.stats||{};renderFolders();renderFull();el.meta.textContent=`${state.stats.videos||0} 个视频 · ${state.stats.images||0} 张图片 · 首页只展示 ${state.items.length} 个视频`;}
  async function loadList(view,{append=false}={}){const token=++state.requestToken,offset=append?state.items.length:0;state.route=view;let url=`/api/smart/list?view=${encodeURIComponent(view)}&offset=${offset}&limit=30`;if(view==='folder')url+=`&folder=${encodeURIComponent(state.folder)}`;if(view==='search')url+=`&q=${encodeURIComponent(state.query)}`;const d=await api(url);if(token!==state.requestToken)return;const batch=d.items||[];if(append){state.items.push(...batch);appendCards(batch);}else{state.items=batch;renderFull();}state.hasMore=!!d.hasMore;el.more.classList.toggle('hidden',!state.hasMore);el.title.textContent=d.title||'媒体';el.meta.textContent=`${d.total||0} 项 · 浏览器当前只保留 ${state.items.length} 项`;el.hint.textContent=state.hasMore?'每次只取 30 项':'已到末尾';navActive(view);}
  function openFolder(folder){state.folder=folder;state.query='';el.search.value='';loadList('folder').catch(e=>toast(e.message));}
  function searchNow(q){const t=String(q||'').trim();if(!t)return loadHome().catch(e=>toast(e.message));state.query=t;state.folder='';loadList('search').catch(e=>toast(e.message));}
  async function loadClientSubset(kind){state.route=kind;state.folder='';state.query='';navActive(kind);const ids=kind==='favorite'?[...state.favorites]:Object.entries(state.progress).filter(([,p])=>p?.time>5).map(([id])=>id);el.title.textContent=kind==='favorite'?'收藏':'继续观看';el.meta.textContent=ids.length?`共 ${ids.length} 项`:'这里还没有内容';el.hint.textContent='本机记录';state.hasMore=false;if(!ids.length){state.items=[];renderFull();return;}const d=await api(`/api/smart/by-ids?ids=${encodeURIComponent(ids.slice(0,120).join('\n'))}`);state.items=d.items||[];renderFull();}

  function toggleFavorite(id){state.favorites.has(id)?state.favorites.delete(id):state.favorites.add(id);saveFav();if(state.current?.id===id)updateViewerFav();}
  function updateViewerFav(){el.favorite.textContent=state.current&&state.favorites.has(state.current.id)?'★ 已收藏':'☆ 收藏';}
  function openViewer(item){state.current=item;el.video.src=item.url;el.viewerTitle.textContent=item.name;el.viewerPath.textContent=item.path;el.viewerTags.innerHTML=(item.tags||[]).map(t=>`<span>#${esc(t)}</span>`).join('');el.manageTags.value=(item.tags||[]).join(', ');el.renameInput.value=item.stem||item.name.replace(/\.[^.]+$/,'');el.moveInput.value=item.folder||'';el.managePanel.classList.add('hidden');updateViewerFav();el.viewer.showModal();const p=state.progress[item.id];el.video.addEventListener('loadedmetadata',function restore(){el.video.removeEventListener('loadedmetadata',restore);if(p?.time&&p.time<el.video.duration-3)el.video.currentTime=p.time;el.video.play().catch(()=>{});});}
  function persistProgress(force=false){if(!state.current||!Number.isFinite(el.video.duration)||el.video.duration<=0)return;const now=Date.now();if(!force&&now-lastProgressWrite<3000)return;lastProgressWrite=now;state.progress[state.current.id]={time:el.video.currentTime,duration:el.video.duration,at:now};saveProgress();}
  function closeViewer(){persistProgress(true);el.video.pause();el.video.removeAttribute('src');el.video.load();if(el.viewer.open)el.viewer.close();state.current=null;}
  function openSingleImage(item){state.pack={title:item.name,images:[item]};state.packIndex=0;renderReader();el.reader.showModal();}
  async function openPack(folder){const d=await api(`/api/smart/pack?folder=${encodeURIComponent(folder)}`);state.pack=d;state.packIndex=0;renderReader();el.reader.showModal();}
  function renderReader(){if(!state.pack?.images?.length)return;const i=state.pack.images[state.packIndex];el.readerImage.src=i.url;el.readerTitle.textContent=state.pack.title||i.name;el.readerCounter.textContent=`${state.packIndex+1} / ${state.pack.images.length}`;const next=state.pack.images[state.packIndex+1];if(next){const pre=new Image();pre.src=next.url;}}
  function stepReader(d){if(!state.pack?.images?.length)return;state.packIndex=(state.packIndex+d+state.pack.images.length)%state.pack.images.length;renderReader();}

  function openTagDialog(item){state.tagTarget=item;el.tagDialogName.textContent=item.name;el.tagDialogInput.value=(item.tags||[]).join(', ');el.tagDialog.showModal();setTimeout(()=>el.tagDialogInput.focus(),20);}
  async function saveTagQuick(){const item=state.tagTarget;if(!item)return;const tags=el.tagDialogInput.value.split(/[,，]/).map(x=>x.trim()).filter(Boolean);try{await manage({action:'set_tags',paths:[item.id],tags,mode:'replace'});item.tags=tags;updateTagStrip(item);el.tagDialog.close();toast('标签已保存');}catch(e){toast(e.message);}}
  async function rescan(){el.rescan.disabled=true;el.rescan.textContent='扫描中…';try{await api('/api/smart/rescan');await loadHome();toast('索引已刷新');}catch(e){toast(e.message);}finally{el.rescan.disabled=false;el.rescan.textContent='重新扫描';}}
  async function migrateClient(oldId,newId){if(oldId!==newId){if(state.favorites.delete(oldId)){state.favorites.add(newId);saveFav();}if(state.progress[oldId]){state.progress[newId]=state.progress[oldId];delete state.progress[oldId];saveProgress();}}await api('/api/smart/rescan');}

  el.favorite.onclick=()=>{if(state.current)toggleFavorite(state.current.id);};el.manage.onclick=()=>el.managePanel.classList.toggle('hidden');
  el.saveTags.onclick=async()=>{if(!state.current)return;const tags=el.manageTags.value.split(/[,，]/).map(x=>x.trim()).filter(Boolean);try{await manage({action:'set_tags',paths:[state.current.id],tags,mode:'replace'});state.current.tags=tags;el.viewerTags.innerHTML=tags.map(t=>`<span>#${esc(t)}</span>`).join('');const listed=state.items.find(x=>x.id===state.current.id);if(listed){listed.tags=tags;updateTagStrip(listed);}toast('标签已保存');}catch(e){toast(e.message);}};
  el.renameBtn.onclick=async()=>{if(!state.current)return;const old=state.current.id;try{const d=await manage({action:'rename',path:old,stem:el.renameInput.value.trim()}),m=d.moved?.[0];if(m){await migrateClient(old,m.new);closeViewer();toast('已改名');state.route==='folder'?openFolder(state.folder):loadHome();}}catch(e){toast(e.message);}};
  el.moveBtn.onclick=async()=>{if(!state.current)return;const old=state.current.id;try{const d=await manage({action:'move',paths:[old],folder:el.moveInput.value.trim(),create:true}),m=d.moved?.[0];if(m){await migrateClient(old,m.new);closeViewer();toast('已移动');state.route==='folder'?openFolder(state.folder):loadHome();}}catch(e){toast(e.message);}};
  el.video.addEventListener('timeupdate',()=>persistProgress(false));el.video.addEventListener('pause',()=>persistProgress(true));el.closeViewer.onclick=closeViewer;el.viewer.addEventListener('cancel',e=>{e.preventDefault();closeViewer();});
  el.closeReader.onclick=()=>el.reader.close();el.readerPrev.onclick=()=>stepReader(-1);el.readerNext.onclick=()=>stepReader(1);el.reader.addEventListener('cancel',e=>{e.preventDefault();el.reader.close();});
  el.closeTagDialog.onclick=el.cancelTagDialog.onclick=()=>el.tagDialog.close();el.saveTagDialog.onclick=saveTagQuick;el.tagDialogInput.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();saveTagQuick();}});
  el.more.onclick=()=>loadList(state.route,{append:true}).catch(e=>toast(e.message));el.rescan.onclick=rescan;el.brand.onclick=()=>loadHome().catch(e=>toast(e.message));el.clearSearch.onclick=()=>{el.search.value='';loadHome().catch(e=>toast(e.message));};
  el.search.addEventListener('input',()=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>searchNow(el.search.value),240);});
  $$('.main-nav button').forEach(b=>b.onclick=()=>{const r=b.dataset.route;if(r==='home')loadHome();else if(r==='root'){state.folder='';loadList('folder');}else if(r==='favorite'||r==='continue')loadClientSubset(r);else loadList(r);});
  document.addEventListener('keydown',e=>{if(el.reader.open&&!['INPUT','TEXTAREA'].includes(e.target.tagName)){if(e.key==='ArrowLeft')stepReader(-1);if(e.key==='ArrowRight')stepReader(1);}if(el.viewer.open&&e.key==='Escape'&&!['INPUT','TEXTAREA'].includes(e.target.tagName)){e.preventDefault();closeViewer();}});
  window.addEventListener('beforeunload',()=>{persistProgress(true);clearThumbWork();});
  loadHome().catch(e=>{el.meta.textContent='索引加载失败';toast(e.message);});
})();
